# Generated by Django 2.1.7 on 2019-02-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('Individual', 'individual'), ('Company', 'company')], default='individual', max_length=100),
        ),
    ]
