# Generated by Django 2.1.7 on 2019-02-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_accounts', '0002_auto_20190221_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], default='individual', max_length=100),
        ),
    ]
